[config.wallpaper]
set = true
command = "swww"
arguments = ["img", "--transition-type", "wipe", "--transition-fps", "60"]

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/src/colors.conf"
post_hook = "hyprctl reload"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.mako]
input_path = "~/.config/matugen/templates/mako-colors"
output_path = "~/.config/mako/theme"
post_hook = "makoctl reload"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/theme.rasi"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty-aeterm.conf"
output_path = "~/.config/ghostty/themes/Aeterm"
post_hook = "pkill -SIGUSR2 ghostty"
